services:
  coqui-tts-api:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - DEVICE=${DEVICE:-auto}
      - PYTHONUNBUFFERED=1
      - TORCH_DISABLE_WEIGHTS_ONLY=1
    volumes:
      - ./cache:/app/cache
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s  # Extended for model loading
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      coqui-tts-api:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - production